name = "a_beautiful_world"
description = "World generation and evolution"
version = "0.1.0-dev"

authors = ["Kaitlyn"]
maintainers = ["Kaitlyn <kaitlyn.buffler@tutamail.com>"]
maintainers-logins = ["Akutchi"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["gtkada", "gui", "ada"]

executables = ["a_beautiful_world"]

[[depends-on]]
gtkada = "^22.0.0"

[[depends-on]]
image_io = "^20240725.0.0"
